name: install action

runs:
  using: composite
  steps:
    - name: Checkout the repo
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: 0

    - name: Setup Node and pnpm
      uses: jdx/mise-action@v2

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile --strict-peer-dependencies --filter=ccip-js --filter=ccip-react-components
      shell: bash